# Generated by Django 3.1.1 on 2021-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('is_liked', models.BooleanField()),
            ],
        ),
    ]
