# Generated by Django 3.1.1 on 2021-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
